### ISSUE TITLE
退币请求已经超过两周了，两周内没有任何邮件回应，两周内没有返还eth！

### ISSUE THREAD

**Issue by ouyangfeng** [OwnershipFoundation/ownership#3]
![image](https://user-images.githubusercontent.com/11793265/32034093-208e3566-b9d6-11e7-9d44-8b36299032c3.png)
这是两周前的  一封邮件，诱骗我把代币打回这个地址！
之后我将代币打回
从此以后ownership再也没有给我回复过邮件，我发了无数封邮件都石沉大海！
我会向全世界，全币圈，揭露你们，人肉你们！

**Comment by caoqiaolin** [comment]
楼主收到退币了吗？他们是不是跑路了？
